// <auto-generated />
using System;
using CDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDatos.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251019221652_AddCanchasBackend")]
    partial class AddCanchasBackend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entidades.Canchas", b =>
                {
                    b.Property<int>("Cancha_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cancha_ID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("Deporte_ID")
                        .HasColumnType("int");

                    b.HasKey("Cancha_ID");

                    b.ToTable("Canchas");

                    b.HasData(
                        new
                        {
                            Cancha_ID = 1,
                            Activa = true,
                            Deporte_ID = 1
                        },
                        new
                        {
                            Cancha_ID = 2,
                            Activa = true,
                            Deporte_ID = 2
                        },
                        new
                        {
                            Cancha_ID = 3,
                            Activa = true,
                            Deporte_ID = 3
                        },
                        new
                        {
                            Cancha_ID = 4,
                            Activa = true,
                            Deporte_ID = 4
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Deportes", b =>
                {
                    b.Property<int>("Deporte_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Deporte_ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Deporte_ID");

                    b.ToTable("Deportes");

                    b.HasData(
                        new
                        {
                            Deporte_ID = 1,
                            Nombre = "Fútbol"
                        },
                        new
                        {
                            Deporte_ID = 2,
                            Nombre = "Básquet"
                        },
                        new
                        {
                            Deporte_ID = 3,
                            Nombre = "Vóley"
                        },
                        new
                        {
                            Deporte_ID = 4,
                            Nombre = "Tenis"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Productos", b =>
                {
                    b.Property<int>("Producto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Producto_ID"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Proveedor_ID")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Producto_ID");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Producto_ID = 1,
                            Precio = 500m,
                            Proveedor_ID = 1,
                            TipoProducto = "Agua Mineral"
                        },
                        new
                        {
                            Producto_ID = 2,
                            Precio = 800m,
                            Proveedor_ID = 2,
                            TipoProducto = "Papas Fritas"
                        },
                        new
                        {
                            Producto_ID = 3,
                            Precio = 700m,
                            Proveedor_ID = 3,
                            TipoProducto = "Gaseosa"
                        },
                        new
                        {
                            Producto_ID = 4,
                            Precio = 600m,
                            Proveedor_ID = 4,
                            TipoProducto = "Barrita Energética"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Proveedores", b =>
                {
                    b.Property<int>("Proveedor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Proveedor_ID"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Proveedor_ID");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Proveedor_ID = 1,
                            Direccion = "Buenos aires 510",
                            Email = "prov1@test.com",
                            Nombre = "Proveedor1",
                            Telefono = "1111"
                        },
                        new
                        {
                            Proveedor_ID = 2,
                            Direccion = "Buenos aires 511",
                            Email = "prov2@test.com",
                            Nombre = "Proveedor2",
                            Telefono = "2222"
                        },
                        new
                        {
                            Proveedor_ID = 3,
                            Direccion = "Buenos aires 512",
                            Email = "prov3@test.com",
                            Nombre = "Proveedor3",
                            Telefono = "3333"
                        },
                        new
                        {
                            Proveedor_ID = 4,
                            Direccion = "Buenos aires 513",
                            Email = "prov4@test.com",
                            Nombre = "Proveedor4",
                            Telefono = "4444"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.TurnoProducto", b =>
                {
                    b.Property<int>("TurnoProducto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoProducto_ID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Producto_ID")
                        .HasColumnType("int");

                    b.Property<int>("Turno_ID")
                        .HasColumnType("int");

                    b.HasKey("TurnoProducto_ID");

                    b.ToTable("TurnoProductos");

                    b.HasData(
                        new
                        {
                            TurnoProducto_ID = 1,
                            Cantidad = 2,
                            Producto_ID = 1,
                            Turno_ID = 1
                        },
                        new
                        {
                            TurnoProducto_ID = 2,
                            Cantidad = 1,
                            Producto_ID = 2,
                            Turno_ID = 2
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Turnos", b =>
                {
                    b.Property<int>("Turno_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Turno_ID"));

                    b.Property<int>("Cancha_ID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario_ID")
                        .HasColumnType("int");

                    b.HasKey("Turno_ID");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            Turno_ID = 1,
                            Cancha_ID = 1,
                            Estado = "Confirmado",
                            HoraFin = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2024, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Usuario_ID = 1
                        },
                        new
                        {
                            Turno_ID = 2,
                            Cancha_ID = 2,
                            Estado = "Confirmado",
                            HoraFin = new DateTime(2024, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Usuario_ID = 2
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Usuario_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usuario_ID"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Usuario_ID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Usuario_ID = 1,
                            Contraseña = "1111",
                            Email = "usuario1@test.com",
                            Nombre = "Usuario1",
                            NumeroTelefono = "3493112233",
                            Rol = "Cliente"
                        },
                        new
                        {
                            Usuario_ID = 2,
                            Contraseña = "2222",
                            Email = "usuario2@test.com",
                            Nombre = "Usuario2",
                            NumeroTelefono = "3493112244",
                            Rol = "Administrador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
