// <auto-generated />
using System;
using CDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDatos.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entidades.Administrador", b =>
                {
                    b.Property<int>("Admin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_ID"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Admin_ID");

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            Admin_ID = 1,
                            Contraseña = "1234",
                            Email = "admin1@test.com",
                            IsSuperAdmin = true,
                            Nombre = "Admin1"
                        },
                        new
                        {
                            Admin_ID = 2,
                            Contraseña = "1234",
                            Email = "admin2@test.com",
                            IsSuperAdmin = false,
                            Nombre = "Admin2"
                        },
                        new
                        {
                            Admin_ID = 3,
                            Contraseña = "1234",
                            Email = "admin3@test.com",
                            IsSuperAdmin = false,
                            Nombre = "Admin3"
                        },
                        new
                        {
                            Admin_ID = 4,
                            Contraseña = "1234",
                            Email = "admin4@test.com",
                            IsSuperAdmin = true,
                            Nombre = "Admin4"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Canchas", b =>
                {
                    b.Property<int>("Cancha_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cancha_ID"));

                    b.Property<int>("Deporte_ID")
                        .HasColumnType("int");

                    b.HasKey("Cancha_ID");

                    b.HasIndex("Deporte_ID");

                    b.ToTable("Canchas");

                    b.HasData(
                        new
                        {
                            Cancha_ID = 1,
                            Deporte_ID = 1
                        },
                        new
                        {
                            Cancha_ID = 2,
                            Deporte_ID = 2
                        },
                        new
                        {
                            Cancha_ID = 3,
                            Deporte_ID = 3
                        },
                        new
                        {
                            Cancha_ID = 4,
                            Deporte_ID = 4
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Clientes", b =>
                {
                    b.Property<int>("Cliente_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cliente_ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("Cliente_ID");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Cliente_ID = 1,
                            Nombre = "Juan Perez",
                            NumeroTelefono = 111111111
                        },
                        new
                        {
                            Cliente_ID = 2,
                            Nombre = "Ana Gomez",
                            NumeroTelefono = 222222222
                        },
                        new
                        {
                            Cliente_ID = 3,
                            Nombre = "Carlos Lopez",
                            NumeroTelefono = 333333333
                        },
                        new
                        {
                            Cliente_ID = 4,
                            Nombre = "Maria Diaz",
                            NumeroTelefono = 444444444
                        });
                });

            modelBuilder.Entity("Shared.Entidades.ConsumicionProducto", b =>
                {
                    b.Property<int>("ConsumicionProducto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumicionProducto_ID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Consumicion_ID")
                        .HasColumnType("int");

                    b.Property<int>("Producto_ID")
                        .HasColumnType("int");

                    b.Property<int?>("TurnosTurno_ID")
                        .HasColumnType("int");

                    b.HasKey("ConsumicionProducto_ID");

                    b.HasIndex("Consumicion_ID");

                    b.HasIndex("Producto_ID");

                    b.HasIndex("TurnosTurno_ID");

                    b.ToTable("consumicionProductos");

                    b.HasData(
                        new
                        {
                            ConsumicionProducto_ID = 1,
                            Cantidad = 2,
                            Consumicion_ID = 1,
                            Producto_ID = 1
                        },
                        new
                        {
                            ConsumicionProducto_ID = 2,
                            Cantidad = 1,
                            Consumicion_ID = 2,
                            Producto_ID = 2
                        },
                        new
                        {
                            ConsumicionProducto_ID = 3,
                            Cantidad = 3,
                            Consumicion_ID = 3,
                            Producto_ID = 3
                        },
                        new
                        {
                            ConsumicionProducto_ID = 4,
                            Cantidad = 2,
                            Consumicion_ID = 4,
                            Producto_ID = 4
                        });
                });

            modelBuilder.Entity("Shared.Entidades.ConsumicionXturno", b =>
                {
                    b.Property<int>("ConsumicionXturno_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumicionXturno_ID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Producto_ID")
                        .HasColumnType("int");

                    b.Property<int>("Turno_ID")
                        .HasColumnType("int");

                    b.HasKey("ConsumicionXturno_ID");

                    b.HasIndex("Producto_ID");

                    b.HasIndex("Turno_ID");

                    b.ToTable("consumicionXturnos");

                    b.HasData(
                        new
                        {
                            ConsumicionXturno_ID = 1,
                            Cantidad = 1,
                            Producto_ID = 1,
                            Turno_ID = 1
                        },
                        new
                        {
                            ConsumicionXturno_ID = 2,
                            Cantidad = 2,
                            Producto_ID = 2,
                            Turno_ID = 2
                        },
                        new
                        {
                            ConsumicionXturno_ID = 3,
                            Cantidad = 3,
                            Producto_ID = 3,
                            Turno_ID = 3
                        },
                        new
                        {
                            ConsumicionXturno_ID = 4,
                            Cantidad = 4,
                            Producto_ID = 4,
                            Turno_ID = 4
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Consumiciones", b =>
                {
                    b.Property<int>("Consumicion_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Consumicion_ID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Consumicion_ID");

                    b.ToTable("Consumiciones");

                    b.HasData(
                        new
                        {
                            Consumicion_ID = 1,
                            Cantidad = 2,
                            Precio = 1000m
                        },
                        new
                        {
                            Consumicion_ID = 2,
                            Cantidad = 3,
                            Precio = 1500m
                        },
                        new
                        {
                            Consumicion_ID = 3,
                            Cantidad = 1,
                            Precio = 500m
                        },
                        new
                        {
                            Consumicion_ID = 4,
                            Cantidad = 5,
                            Precio = 2500m
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Deportes", b =>
                {
                    b.Property<int>("Deporte_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Deporte_ID"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Deporte_ID");

                    b.ToTable("Deportes");

                    b.HasData(
                        new
                        {
                            Deporte_ID = 1,
                            Tipo = "Fútbol"
                        },
                        new
                        {
                            Deporte_ID = 2,
                            Tipo = "Básquet"
                        },
                        new
                        {
                            Deporte_ID = 3,
                            Tipo = "Vóley"
                        },
                        new
                        {
                            Deporte_ID = 4,
                            Tipo = "Tenis"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Elementos", b =>
                {
                    b.Property<int>("Elemento_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Elemento_ID"));

                    b.Property<int>("Cancha_ID")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Elemento_ID");

                    b.HasIndex("Cancha_ID");

                    b.ToTable("Elementos");

                    b.HasData(
                        new
                        {
                            Elemento_ID = 1,
                            Cancha_ID = 1,
                            Cantidad = 10,
                            Nombre = "Pelotas Fútbol"
                        },
                        new
                        {
                            Elemento_ID = 2,
                            Cancha_ID = 2,
                            Cantidad = 8,
                            Nombre = "Pelotas Básquet"
                        },
                        new
                        {
                            Elemento_ID = 3,
                            Cancha_ID = 3,
                            Cantidad = 12,
                            Nombre = "Pelotas Vóley"
                        },
                        new
                        {
                            Elemento_ID = 4,
                            Cancha_ID = 4,
                            Cantidad = 6,
                            Nombre = "Raquetas"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Productos", b =>
                {
                    b.Property<int>("Producto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Producto_ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Proveedor_ID")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Producto_ID");

                    b.HasIndex("Proveedor_ID");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Producto_ID = 1,
                            Descripcion = "Agua Mineral",
                            Precio = 500m,
                            Proveedor_ID = 1,
                            Tipo = "Bebida"
                        },
                        new
                        {
                            Producto_ID = 2,
                            Descripcion = "Papas Fritas",
                            Precio = 800m,
                            Proveedor_ID = 2,
                            Tipo = "Snack"
                        },
                        new
                        {
                            Producto_ID = 3,
                            Descripcion = "Gaseosa",
                            Precio = 700m,
                            Proveedor_ID = 3,
                            Tipo = "Bebida"
                        },
                        new
                        {
                            Producto_ID = 4,
                            Descripcion = "Barrita Energética",
                            Precio = 600m,
                            Proveedor_ID = 4,
                            Tipo = "Snack"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Proveedores", b =>
                {
                    b.Property<int>("Proveedor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Proveedor_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Proveedor_ID");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Proveedor_ID = 1,
                            Email = "prov1@test.com",
                            Nombre = "Proveedor1",
                            Telefono = "1111"
                        },
                        new
                        {
                            Proveedor_ID = 2,
                            Email = "prov2@test.com",
                            Nombre = "Proveedor2",
                            Telefono = "2222"
                        },
                        new
                        {
                            Proveedor_ID = 3,
                            Email = "prov3@test.com",
                            Nombre = "Proveedor3",
                            Telefono = "3333"
                        },
                        new
                        {
                            Proveedor_ID = 4,
                            Email = "prov4@test.com",
                            Nombre = "Proveedor4",
                            Telefono = "4444"
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Turnos", b =>
                {
                    b.Property<int>("Turno_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Turno_ID"));

                    b.Property<int>("Admin_ID")
                        .HasColumnType("int");

                    b.Property<int>("Cancha_ID")
                        .HasColumnType("int");

                    b.Property<int>("Cliente_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Turno_ID");

                    b.HasIndex("Admin_ID");

                    b.HasIndex("Cancha_ID");

                    b.HasIndex("Cliente_ID");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            Turno_ID = 1,
                            Admin_ID = 1,
                            Cancha_ID = 1,
                            Cliente_ID = 1,
                            HoraFin = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2024, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Turno_ID = 2,
                            Admin_ID = 2,
                            Cancha_ID = 2,
                            Cliente_ID = 2,
                            HoraFin = new DateTime(2024, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Shared.Entidades.Canchas", b =>
                {
                    b.HasOne("Shared.Entidades.Deportes", "Deporte")
                        .WithMany("Canchas")
                        .HasForeignKey("Deporte_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deporte");
                });

            modelBuilder.Entity("Shared.Entidades.ConsumicionProducto", b =>
                {
                    b.HasOne("Shared.Entidades.Consumiciones", "Consumicion")
                        .WithMany("ConsumicionProductos")
                        .HasForeignKey("Consumicion_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entidades.Productos", "Producto")
                        .WithMany("ConsumicionProductos")
                        .HasForeignKey("Producto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entidades.Turnos", null)
                        .WithMany("ConsumicionProductos")
                        .HasForeignKey("TurnosTurno_ID");

                    b.Navigation("Consumicion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Shared.Entidades.ConsumicionXturno", b =>
                {
                    b.HasOne("Shared.Entidades.Productos", "Productos")
                        .WithMany()
                        .HasForeignKey("Producto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entidades.Turnos", "Turnos")
                        .WithMany()
                        .HasForeignKey("Turno_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Shared.Entidades.Elementos", b =>
                {
                    b.HasOne("Shared.Entidades.Canchas", "Canchas")
                        .WithMany("Elementos")
                        .HasForeignKey("Cancha_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Shared.Entidades.Productos", b =>
                {
                    b.HasOne("Shared.Entidades.Proveedores", "Proveedores")
                        .WithMany("Productos")
                        .HasForeignKey("Proveedor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Shared.Entidades.Turnos", b =>
                {
                    b.HasOne("Shared.Entidades.Administrador", "Administrador")
                        .WithMany("Turnos")
                        .HasForeignKey("Admin_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entidades.Canchas", "Canchas")
                        .WithMany("Turnos")
                        .HasForeignKey("Cancha_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entidades.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("Cliente_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Canchas");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Shared.Entidades.Administrador", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Shared.Entidades.Canchas", b =>
                {
                    b.Navigation("Elementos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Shared.Entidades.Consumiciones", b =>
                {
                    b.Navigation("ConsumicionProductos");
                });

            modelBuilder.Entity("Shared.Entidades.Deportes", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Shared.Entidades.Productos", b =>
                {
                    b.Navigation("ConsumicionProductos");
                });

            modelBuilder.Entity("Shared.Entidades.Proveedores", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Shared.Entidades.Turnos", b =>
                {
                    b.Navigation("ConsumicionProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
